# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26cb7503ee0f28f1a58583b7405bdc605e2ca11103cef928b3e787d429ca542c90240488f0124ee70dc95705f482ae3c960e6580415b868549db566c80369e21

test:
  secret_key_base: a0762c51eecf5932c156bf32f3737bf541d67781cdf31ea733dafe98cfb6fd9a66cd56d99b2f091525d56146b0c55d6264ea3f90ca03a412c62f5b2200f928b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
